openapi: 3.0.3
info:
  title: Akros Marketplace
  version: 1.0.0-SNAPSHOT
  description: YAML Swagger Configuration for the Akros Marketplace

paths:
  /listFieldTypeDefinition:
    get:
      summary: List the field type definitions
      description: helper function only
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FieldTypeDefinitionResponseDTO'

  /categories:
    get:
      summary: List categories
      description: used for primary search page
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CategoryResponseDTO'

  /topics/{topicId}:
    get:
      summary: Load a topic 
      description: Load a topic
      parameters:
        - name: topicId
          in: path
          required: true
          description: Primary Key ID to Topic.
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicLoadResponseDTO'
  /topics:
    post:
      summary: Save a topic 
      description: Save a topic
      requestBody:
        description: All values to save a topic
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicSaveRequestDTO'
        required: true
      responses:
        200:
          description: OK
    delete:
      summary: Delete a topic 
      description: Delete a topic
      parameters:
        - name: topicId
          in: path
          required: true
          description: Primary Key ID to Topic.
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK

  #/topic-searches:
  /topics/search:
    post:
      summary: Search for topics
      description: Search for topics
      requestBody:
        description: All fields for search query
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicSearchRequestDTO'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicSearchListResponseDTO'

components:
  schemas:
    FieldTypeDefinitionResponseDTO:
      type: object
      properties:
        fieldTypeDefinitionId:
          type: integer
          format: int32
        description:
          type: string
          example: Parkplatz

    CategoryResponseDTO:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
        key:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldResponseDTO'

    FieldResponseDTO:
      type: object
      properties:
        fieldId:
          type: integer
          format: int64
        fieldTypeDefinitionId:
          type: integer
          format: int32
        key:
          type: string
        sortNumber:
          type: integer
        minValue:
          type: integer
          example: 5
        maxValue:
          type: integer
          example: 5
        searchable:
          type: boolean
        request:
          type: boolean
        offer:
          type: boolean
        creation:
          type: boolean
        fieldOptions:
          type: array
          items:
            $ref: '#/components/schemas/FieldOptionResponseDTO'

    FieldOptionResponseDTO:
      type: object
      properties:
        fieldOptionId:
          type: integer
          format: int64
        key:
          type: string
        sortNumber:
          type: integer

    TopicSaveRequestDTO:
      type: object
      properties:
        topicId:
          type: integer
          format: int64
        categoryId:
          type: integer
          format: int64
        requestOrOffer:
          type: boolean
        topicValues:
          type: array
          items:
            $ref: '#/components/schemas/TopicValueSaveRequestDTO'

    TopicValueSaveRequestDTO:
      type: object
      properties:
        fieldTypeId:
          type: integer
          format: int64
        value:
          type: string

    TopicLoadResponseDTO:
      type: object
      properties:
        topicId:
          type: integer
          format: int64
        categoryId:
          type: integer
          format: int64
        requestOrOffer:
          type: boolean
        topicValues:
          type: array
          items:
            $ref: '#/components/schemas/TopicValueLoadResponseDTO'

    TopicValueLoadResponseDTO:
      type: object
      properties:
        topicValueId:
          type: integer
          format: int64
        fieldId:
          type: integer
          format: int64
        fieldDescription:
          type: string
          example: Beschreibung
        fieldShortDescription:
          type: string
          example: Beschreibung
        fieldTypeDefinitionId:
          type: integer
          format: int32
        fieldTypeDefinitionDescription:
          type: string
          example: Number
        minValue:
          type: integer
          example: 5
        maxValue:
          type: integer
          example: 5
        value:
          type: string
        fieldTypeOptions:
          type: array
          items:
            $ref: '#/components/schemas/FieldOptionResponseDTO'

    TopicSearchRequestDTO:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
        requestOrOffer:
          type: boolean
        searchValues:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchFieldValuesRequestDTO'

    TopicSearchFieldValuesRequestDTO:
      type: object
      properties:
        fieldId:
          type: integer
          format: int64
        valueNumFrom:
          type: double
          format: int64
        valueNumTo:
          type: double
          format: int64
        value:
          type: string

    TopicSearchListResponseDTO:
      type: object
      properties:
        columnHeader:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchColumnHeaderResponseDTO'
        topics:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchResponseDTO'

    TopicSearchColumnHeaderResponseDTO:
      type: object
      properties:
        fieldId:
          type: integer
          format: int64
        description:
          type: string
          example: Beschreibung
        shortDescription:
          type: string
          example: Beschreibung der Unterkunft

    TopicSearchResponseDTO:
      type: object
      properties:
        topicId:
          type: integer
          format: int64
        topicValues:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchValueResponseDTO'

    TopicSearchValueResponseDTO:
      type: object
      properties:
        topicId:
          type: integer
          format: int64
        fieldId:
          type: integer
          format: int64
        value:
          type: string
        fieldDefinitionId:
          type: integer
          format: int32
        fieldDefinitionDescription:
          type: string
          example: Number
