openapi: 3.0.3
info:
  title: Akros Marketplace
  version: 1.0.0
  x-api-id: e1208a31-c22b-12d4-2a88-72c398d3ac31
  x-audience: company-internal
  description: YAML Swagger Configuration for the Akros Marketplace
  contact:
    name: Akros Marketplace API Support
    url: https://www.akros.ch/kontakt/
    email: support@example.com

paths:
  /list-field-type-definitions:
    get:
      summary: List the field type definitions
      description: helper function only
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldTypeDefinitionResponseDTO'

  /categories:
    get:
      summary: List categories
      description: used for primary search page
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponseDTO'

  /topics/{topicId}:
    get:
      summary: Load a topic 
      description: Load a topic
      parameters:
        - name: topicId
          in: path
          required: true
          description: Primary Key ID to Topic.
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicLoadResponseDTO'
  /topics:
    post:
      summary: Save a topic 
      description: Save a topic
      requestBody:
        description: All values to save a topic
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicSaveRequestDTO'
        required: true
      responses:
        200:
          description: OK
    delete:
      summary: Delete a topic 
      description: Delete a topic
      parameters:
        - name: topicId
          in: path
          required: true
          description: Primary Key ID to Topic.
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK

  #/topic-searches:
  /topics/searches:
    post:
      summary: Search for topics
      description: Search for topics
      requestBody:
        description: All fields for search query
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicSearchRequestDTO'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicSearchListResponseDTO'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:

    FieldTypeDefinitionResponseDTO:
      type: object
      properties:
        field_types:
          type: array
          items:
            $ref: '#/components/schemas/FieldTypeDefinitionDTO'

    FieldTypeDefinitionDTO:
      type: object
      properties:
        field_type_definition_id:
          type: integer
          format: int32
        description:
          type: string

    CategoryResponseDTO:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDTO'

    CategoryDTO:
      type: object
      properties:
        category_id:
          type: integer
          format: int64
        key:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldResponseDTO'

    FieldResponseDTO:
      type: object
      properties:
        field_id:
          type: integer
          format: int64
        field_type_definition_id:
          type: integer
          format: int32
        key:
          type: string
        sort_number:
          type: integer
          format: int32
        min_value:
          type: integer
          format: int32
        max_value:
          type: integer
          format: int32
        searchable:
          type: boolean
        request:
          type: boolean
        offer:
          type: boolean
        creation:
          type: boolean
        field_options:
          type: array
          items:
            $ref: '#/components/schemas/FieldOptionResponseDTO'

    FieldOptionResponseDTO:
      type: object
      properties:
        field_option_id:
          type: integer
          format: int64
        key:
          type: string
        sort_number:
          type: integer
          format: int32

    TopicSaveRequestDTO:
      type: object
      properties:
        topic_id:
          type: integer
          format: int64
        category_id:
          type: integer
          format: int64
        request_or_offer:
          type: boolean
        topic_values:
          type: array
          items:
            $ref: '#/components/schemas/TopicValueSaveRequestDTO'

    TopicValueSaveRequestDTO:
      type: object
      properties:
        field_type_id:
          type: integer
          format: int64
        value:
          type: string

    TopicLoadResponseDTO:
      type: object
      properties:
        topic_id:
          type: integer
          format: int64
        category_id:
          type: integer
          format: int64
        request_or_offer:
          type: boolean
        topic_values:
          type: array
          items:
            $ref: '#/components/schemas/TopicValueLoadResponseDTO'

    TopicValueLoadResponseDTO:
      type: object
      properties:
        topic_value_id:
          type: integer
          format: int64
        field_id:
          type: integer
          format: int64
        field_description:
          type: string
          example: Beschreibung
        field_short_description:
          type: string
          example: Beschreibung
        field_type_definition_id:
          type: integer
          format: int32
        field_type_definition_description:
          type: string
          example: Number
        min_value:
          type: integer
          format: int32
        max_value:
          type: integer
          format: int32
        value:
          type: string
        field_type_options:
          type: array
          items:
            $ref: '#/components/schemas/FieldOptionResponseDTO'

    TopicSearchRequestDTO:
      type: object
      properties:
        category_id:
          type: integer
          format: int64
        request_or_offer:
          type: boolean
        search_values:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchFieldValuesRequestDTO'

    TopicSearchFieldValuesRequestDTO:
      type: object
      properties:
        field_id:
          type: integer
          format: int64
        value_num_from:
          type: integer
          format: int32
        value_num_to:
          type: integer
          format: int32
        value:
          type: string

    TopicSearchListResponseDTO:
      type: object
      properties:
        column_header:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchColumnHeaderResponseDTO'
        topics:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchResponseDTO'

    TopicSearchColumnHeaderResponseDTO:
      type: object
      properties:
        field_id:
          type: integer
          format: int64
        description:
          type: string
          example: Beschreibung
        short_description:
          type: string
          example: Beschreibung der Unterkunft

    TopicSearchResponseDTO:
      type: object
      properties:
        topic_id:
          type: integer
          format: int64
        topic_values:
          type: array
          items:
            $ref: '#/components/schemas/TopicSearchValueResponseDTO'

    TopicSearchValueResponseDTO:
      type: object
      properties:
        topic_id:
          type: integer
          format: int64
        field_id:
          type: integer
          format: int64
        value:
          type: string
        field_definition_id:
          type: integer
          format: int32
        field_definition_description:
          type: string
          example: Number

security:
  - bearerAuth: []