spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/am?createDatabaseIfNotExist=true
    username: am
    password: am
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-main.yml
  keycloak_client:
    base_url: http://127.0.0.1:9090
    client_secret: XP0knCLKLhJK8uaEZQg8RRqsENzlywe1

keycloak:
  realm: akros-marketplace
  bearer-only: true
  auth-server-url: http://auth-service:9090
  resource: marketplace
  ssl-required: none
  use-resource-role-mappings: false
  principal-attribute: preferred_username
