azure:
  keyvault:
    client-id: bc8c5b34-1189-4ae3-99fe-bffc0c7b04fc
    enabled: true
    uri: https://am-kv.vault.azure.net/
spring:
  # placeholder values for datasource, otherwise spring blows up
  datasource:
    url: jdbc:postgresql://localhost:5432/am
    username: am
    password: am
  liquibase:
    enabled: false
  keycloak_client:
    base_url: * # TODO add client_secret for prod
    client_secret: : * # TODO add client_secret for prod

keycloak:
  realm: akros-marketplace
  bearer-only: true
  auth-server-url: https://am-keycloak.azurewebsites.net
  resource: marketplace
  ssl-required: none
  use-resource-role-mappings: false
  principal-attribute: preferred_username
