version: "3.9"

services:
  client-ui:
    container_name: client-ui
    build:
      context: ../..
      dockerfile: ./am-ui/Dockerfile.local
    ports:
      - 4200:443
    environment:
      - OWN_URL=https://localhost:4200
      - NGINX_UPSTREAM_MARKETPLACE_SERVICE=https://marketplace-service:8443
      - NGINX_UPSTREAM_AUTH_SERVICE=https://auth-service:9443
      - NGINX_UPSTREAM_MONITORING_SERVICE=http://grafana:3000
      - MARKETPLACE_SERVICE=https://localhost:8443
      - AUTH_SERVICE=https://localhost:9443
      - MONITORING_SERVICE=http://localhost:3000
      - USERS_MANAGEMENT_SERVICE=http://localhost:9090
      - SIGNON_AUTHORITY=https://login.microsoftonline.com/45a8141c-94c3-4fde-9cf3-0cfcc10ad529
      - SIGNON_CLIENT_ID=9f9965aa-840d-4c88-8121-eac081ee2dd8
      - KEYCLOAK_ISSUER=http://127.0.0.1:9090/realms/akros-marketplace
      - KEYCLOAK_REFRESH_REDIRECT_URI=https://localhost:4200/assets/silent-refresh.html
      - KEYCLOAK_CLIENT_ID=marketplace
      - KEYCLOAK_DUMMY_CLIENT_SECRET=XP0knCLKLhJK8uaEZQg8RRqsENzlywe1
    networks:
      marketplacenet:
    depends_on:
      marketplace-service:
        condition: service_started
      auth-service:
        condition: service_healthy
  marketplace-service:
    container_name: marketplace-service
    build:
      context: ../..
      dockerfile: ./marketplace-service/Dockerfile.local
    ports:
      - 8443:8443
      - 5005:5005
    environment:
      - POSTGRES_AM_DB_URL=jdbc:postgresql://postgres_am_db:5432/am
      - POSTGRES_AM_DB_USERNAME=am
      - POSTGRES_AM_DB_PASSWORD=am
    networks:
      marketplacenet:
    depends_on:
      auth-service:
        condition: service_healthy
      postgres_am_db:
        condition: service_healthy

  auth-service:
    container_name: auth-service
    build:
      context: ../..
      dockerfile: ./infrastructure/keycloak/Dockerfile.local
    ports:
      - '9090:9090'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloakdb
      - KC_DB_USERNAME=keycloakdb
      - KC_DB_PASSWORD=keycloakdb
    networks:
      marketplacenet:
    depends_on:
      keycloak_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9090/realms/akros-marketplace" ]
      interval: 10s
      timeout: 30s
      retries: 20

  postgres_am_db:
    image: postgres:14.1
    container_name: postgres_am_db
    hostname: postgres_am_db
    deploy:
      mode: global
    environment:
      - POSTGRES_USER=am
      - POSTGRES_PASSWORD=am
      - POSTGRES_DB=am
    volumes:
      - "am_db:/var/lib/postgresql/data"
      - "../db_init_am:/docker-entrypoint-initdb.d/"
    ports:
      - 5432:5432
    networks:
      marketplacenet:
        aliases:
          - postgres_am_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "am", "-U", "am"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak_db:
    image: postgres:14.1
    container_name: keycloak_db
    hostname: keycloak_db
    deploy:
      mode: global
    environment:
      - POSTGRES_USER=keycloakdb
      - POSTGRES_PASSWORD=keycloakdb
      - POSTGRES_DB=keycloakdb
    volumes:
      - "keycloak_db:/var/lib/postgresql/data"
      - "../db_init_keycloakdb:/docker-entrypoint-initdb.d/"
    ports:
      - 5434:5432
    networks:
      marketplacenet:
        aliases:
          - keycloak_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloakdb", "-U", "keycloakdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Use the command "docker-compose --profile monitoring up -d" to start prometheus and grafana services for monitoring
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'
    profiles: ["monitoring"]

  grafana:
    image: grafana/grafana:9.2.2
    container_name: grafana
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    profiles: ["monitoring"]

networks:
  marketplacenet:
volumes:
  keycloak_db:
    name: keycloak_db
  am_db:
    name: am_db
