global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # This is prometheus
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    metrics_path: '/metrics'
    scheme: https
    scrape_interval: 5s
    static_configs:
      - targets: ['am-monitoring-service.azurewebsites.net']

  # This is marketplace-service
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["am-marketplace-service.azurewebsites.net"]