# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:lts as build
RUN apt-get update && apt-get install -y openjdk-11-jdk

# Set the working directory
WORKDIR /usr/local/app/am-ui

# copy only package, package-lock files and api-yaml and install dependencies for caching purposes
COPY ./am-ui/package.json ./
COPY ./am-ui/pnpm-lock.yaml ./
COPY ./am-ui/.npmrc ./
COPY ./am-ui/build_scripts ./build_scripts/
COPY ./am-ui/webcomponents/build_scripts ./webcomponents/build_scripts/
COPY ./am-ui/webcomponents/package.json ./webcomponents/
COPY ./am-ui/webcomponents/pnpm-lock.yaml ./webcomponents/
COPY ./am-ui/webcomponents/create-ad-webcomponent/package.json ./webcomponents/create-ad-webcomponent/
COPY ./am-ui/webcomponents/create-ad-webcomponent/pnpm-lock.yaml ./webcomponents/create-ad-webcomponent/
COPY ./am-ui/webcomponents/search-results-webcomponent/package.json ./webcomponents/search-results-webcomponent/
COPY ./am-ui/webcomponents/search-results-webcomponent/pnpm-lock.yaml ./webcomponents/search-results-webcomponent/
COPY ./am-ui/webcomponents/search-webcomponent/package.json ./webcomponents/search-webcomponent/
COPY ./am-ui/webcomponents/search-webcomponent/pnpm-lock.yaml ./webcomponents/search-webcomponent/

# Add the source code to app
COPY ./api.yaml /usr/local/app/
COPY ./am-ui ./

# Install all the dependencies
RUN npm install -g pnpm
RUN pnpm install

# Generate the build of the application
RUN pnpm build

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest AS deploy

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/am-ui/dist/marketplace-ui /usr/share/nginx/html
COPY ./am-ui/src/cert.pem /usr/share/nginx/cert.pem
COPY ./am-ui/src/cert.key /usr/share/nginx/cert.key
COPY ./am-ui/nginx-prod.conf /etc/nginx/nginx.conf
# Expose port 80
EXPOSE 80
