version: "3"
services:
  postgres:
    image: postgres:14.1
    hostname: postgres_am
    deploy:
      mode: global    
    environment:
      - POSTGRES_USER=am
      - POSTGRES_PASSWORD=am
      - POSTGRES_DB=am
    volumes:
      - "../pg_data_am:/var/lib/postgresql/data"
      - "../db_init_am:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
