# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run a linter across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress

on: [push, pull_request]

jobs:
  docker:
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start containers
        working-directory: ./infrastructure/start_all_local
        run: docker-compose up -d --build postgres_am_db admin-ui marketplace-service postgres_user_db auth-service

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: am-ui/package-lock.json
      - run: npm ci
        working-directory: ./am-ui
      - run: npm run build:webcomponents
        working-directory: ./am-ui
      - run: npm run e2e:headless
        working-directory: ./am-ui
      - name: Stop containers
        working-directory: ./infrastructure/start_all_local
        if: always()
        run: docker-compose down
