# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run a linter across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend

on:
  push:
    paths:
      - "am-ui/**"
  pull_request:
    paths:
      - "am-ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./am-ui

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: am-ui/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test
      - working-directory: ./am-ui/webcomponents
        run: npm ci
      - working-directory: ./am-ui/webcomponents
        run: npm build
      - working-directory: ./am-ui/webcomponents
        run: npm lint
      - working-directory: ./am-ui/webcomponents
        run: npm test

      - uses: azure/docker-login@v1
        with:
          login-server: ampcr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ampcr.azurecr.io/am-ui:${{ github.sha }}
          docker push ampcr.azurecr.io/am-ui:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "am-ui"
          publish-profile: ${{ secrets.AM_UI_PUBLISH_PROFILE }}
          images: "ampcr.azurecr.io/am-ui:${{ github.sha }}"
