# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run a linter across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend

on:
  push:
    paths:
      - "am-ui/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    paths:
      - "am-ui/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./am-ui

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install UI
        run: pnpm install --frozen-lockfile
      - name: Build UI and Webcomponents
        run: pnpm build
      - name: Lint UI
        run: pnpm lint
      - name: Test UI
        run: pnpm test

      - name: Lint Webcomponents
        working-directory: ./am-ui/webcomponents
        run: pnpm lint
      - name: Test Webcomponents
        working-directory: ./am-ui/webcomponents
        run: pnpm test
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: akrosmarketplace.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load cached Docker am-ui layers
        uses: actions/cache@v2
        with:
          path: /tmp/.am-ui-cache
          key: ${{ runner.os }}-am-ui-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-am-ui-

      - name: Build am-ui
        uses: docker/build-push-action@v2
        with:
          file: ./am-ui/Dockerfile
          context: .
          push: true
          target: deploy
          tags: akrosmarketplace.azurecr.io/am-ui:${{ github.sha }}
          cache-from: type=local,src=/tmp/.am-ui-cache
          cache-to: type=local,mode=max,dest=/tmp/.am-ui-cache-new

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "am-ui"
          publish-profile: ${{ secrets.AM_UI_PUBLISH_PROFILE }}
          images: "akrosmarketplace.azurecr.io/am-ui:${{ github.sha }}"

      - name: Move cache
        run: |
          rm -rf /tmp/.am-ui-cache
          mv /tmp/.am-ui-cache-new /tmp/.am-ui-cache