name: Marketplace-Service

on:
  push:
    paths:
      - "infrastructure/keycloak/Dockerfile"
      - ".github/workflows/keycloak-service.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: akrosmarketplace.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build keycloak service
        uses: docker/build-push-action@v2
        with:
          file: ./infrastructure/keycloak/Dockerfile
          context: .
          push: true
          target: deploy
          tags: akrosmarketplace.azurecr.io/am-keycloak-service:${{ github.sha }}

      - name: Deploy keycloak service to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "am-keycloak"
          publish-profile: ${{ secrets.KEYCLOAK_SERVICE_PUBLISH_PROFILE }}
          images: "akrosmarketplace.azurecr.io/am-keycloak-service:${{ github.sha }}"