name: Marketplace-Service

on:
  push:
    paths:
      - "marketplace-service/**"
      - ".github/workflows/marketplace-service.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: akrosmarketplace.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load cached Docker marketplace service layers
        uses: actions/cache@v2
        with:
          path: /tmp/.ms-cache
          key: ${{ runner.os }}-ms-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ms-

      - name: Build marketplace-service
        uses: docker/build-push-action@v2
        with:
          file: ./marketplace-service/Dockerfile
          context: .
          push: true
          target: deploy
          tags: akrosmarketplace.azurecr.io/am-marketplace-service:${{ github.sha }}
          cache-from: type=local,src=/tmp/.ms-cache
          cache-to: type=local,mode=max,dest=/tmp/.ms-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.ms-cache
          mv /tmp/.ms-cache-new /tmp/.ms-cache