name: Java CI with Maven

on:
  push:
    paths:
      - "marketplace-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./marketplace-service

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ampcr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ampcr.azurecr.io/amp-marketplace-service:${{ github.sha }}
          docker push ampcr.azurecr.io/amp-marketplace-service:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "amp-marketplace-service"
          publish-profile: ${{ secrets.MARKETPLACE_SERVICE_PUBLISH_PROFILE }}
          images: "ampcr.azurecr.io/amp-marketplace-service:${{ github.sha }}"
