name: Monitoring-Service

on:
  push:
    paths:
      - "infrastructure/prometheus/Dockerfile"
      - "infrastructure/grafana/Dockerfile"
      - ".github/workflows/monitoring.yml"
    branches:
      - main

jobs:
  prometheus:
    name: Prometheus job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: akrosmarketplace.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build prometheus service
        uses: docker/build-push-action@v2
        with:
          file: ./infrastructure/prometheus/Dockerfile
          context: .
          push: true
          target: deploy
          tags: akrosmarketplace.azurecr.io/am-prometheus-service:${{ github.sha }}

  grafana:
    name: Grafana job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: akrosmarketplace.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build monitoring service
        uses: docker/build-push-action@v2
        with:
          file: ./infrastructure/grafana/Dockerfile
          context: .
          push: true
          target: deploy
          tags: akrosmarketplace.azurecr.io/am-grafana-service:${{ github.sha }}

      - name: Deploy monitoring service to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "am-monitoring-service"
          publish-profile: ${{ secrets.MONITORING_SERVICE_PUBLISH_PROFILE }}
          images: "akrosmarketplace.azurecr.io/am-grafana-service:${{ github.sha }}"