name: "Terraform"

on:
  push:
    branches:
      - main
      - 80-implement-infrastructure-as-code-with-terraform
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_TENANT_CLIENT_ID }}
      TF_VAR_AM_DB_LOGIN: ${{ secrets.POSTGRES_USERNAME }}
      TF_VAR_AM_DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/terraform

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
