name: Run Tests for Marketplace-Service

on:
  push:
    paths:
      - "marketplace-service/**"
      - ".github/workflows/test-backend.yml"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run maven verify
        run: mvn verify